name: Build

on: 
    push:
        branches:
            - main
            - development

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.8'
      - name: Build
        run: swift build
