name: Test

on: 
    push:
        branches:
            - main
            - development

jobs:
  build:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'
      - name: Run Tests
        run: swift test -v
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
